title: 大雄 Flum_X
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://flum-x.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Flum_X # add your name
author-img: david-freeman.jpg # add your photo
about-author: I am an iOS developer. Always hungry to keep learning. # add description
social-github: Flum-X # add your Github handle
social-jianshu: u/a732bb7e9eb3 # add your Linkedin handle
social-weibo: 6004570774/profile?topnav=1&wvr=6&is_all=1
social-email: xfr815113499@126.com# add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
